BGLB.MerberPoint.Web/Controllers/HomeController.cs
using BGLB.MerberPoint.Business;
using BGLB.MerberPoint.Entity.ViewModel;
using System.Web.Mvc;

namespace BGLB.MerberPoint.Web.Controllers
{
    public class HomeController : Controller
    {
        private UsersServive _UsersServive = new UsersServive();

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _UsersServive.Login(viewModel);
                if (result.IsSuccess)
                {
                    var returnUrl = Request["ReturnUrl"];
                    if (!string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("NetWork", "网络繁忙");
                }
                return View();
            }
            else
            {
                ModelState.AddModelError("UserNameOrPassword", "用户名或密码错误");
                return View();
            }
        }

        public ActionResult Logout()
        {
            _UsersServive.Logout();
            return RedirectToAction("Login");
        }

    }
}

BGLB.MerberPoint.Web/Controllers/MeberCardController.cs
using BGLB.MerberPoint.Business;
using BGLB.MerberPoint.Common;
using BGLB.MerberPoint.Entity.ViewModel;
using System.Linq;
using System.Web.Mvc;

namespace BGLB.MerberPoint.Web.Controllers
{
    public class MeberCardController : Controller
    {
        private CardLevelService _CardLevelService = new CardLevelService();
        private MeberCardService _MeberCardService = new MeberCardService();
        /// <summary>
        /// 加载会员列表
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //获取会员等级信息
            var cardLevels = _CardLevelService.GetList(e => true).Select(e => new SelectListItem() { Text = e.CL_LevelName, Value = e.CL_ID.ToString() }).ToList();
            cardLevels.Insert(0, new SelectListItem() { Text = "全部", Value = "0" });
            ViewBag.CardLevel = cardLevels;

            //获取状态信息
            var cardTypeList = EnumHelper.EnumListDic<CardStateTypeEnum>("全部", "0");
            var cardTypeSelectList = new SelectList(cardTypeList, "value", "key");
            ViewBag.CardTypeSelectList = cardTypeSelectList;
            return View();

        }


        public ActionResult GetPagedMeberCardList(GetPagedMeberCardListViewModel viewModel)
        {

            var result = _MeberCardService.GetPagedMeberCardList(viewModel);
            return Json(result.Data);
        }


        public ActionResult Edit(int id = 0)
        {
            var cardLevels = _CardLevelService.GetList(e => true).Select(e => new SelectListItem() { Text = e.CL_LevelName, Value = e.CL_ID.ToString() }).ToList();
            cardLevels.Insert(0, new SelectListItem() { Text = "全部", Value = "0" });
            ViewBag.CardLevel = cardLevels;
            if (id > 0)
            {
                var result = _MeberCardService.GetMerberCardInfo(id.ToString());
                if (result.IsSuccess)
                {
                    return View(result.Data);
                }
                else
                {
                    return Content(result.Msg);
                    //return Redirect()
                }
            }
            else
            {
                return View();
            }
        }

        public ActionResult Create(MerberCardEditViewModel viewModel)
        {
            var result = _MeberCardService.Create(viewModel);
            return Json(result);
        }

        public ActionResult Update(MerberCardEditViewModel viewModel)
        {
            var result = _MeberCardService.Update(viewModel);
            return Json(result);
        }

        public ActionResult Delete(int id)
        {
            var result = _MeberCardService.Delete(id);
            return Json(result);
        }

        public ActionResult SearchWithCardId(string id)
        {
            var result = _MeberCardService.GetMerberCardInfo(id);

            if (result.IsSuccess)
            {
                var jsondata = result.Data as MerberCardTransferViewModel;

                return Json(jsondata);
            }
            else
            {
                return Content(result.Msg);
                //return Redirect()
            }
        }

        public ActionResult Transfer(int id)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                var result = new MerberCardTransferViewModel();
                var memberCardInfo = _MeberCardService.Find(e => e.MC_CardID == id.ToString());

                if (memberCardInfo == null)
                {
                    return Content("查询出错！");

                }
                if (string.IsNullOrWhiteSpace(result.FromMerberCardId))
                {
                    result.FromMerberCardId = memberCardInfo.MC_CardID;
                    result.FromName = memberCardInfo.MC_Name;
                    result.FromPoint = (int)memberCardInfo.MC_Point;
                    result.FromTotalMoney = (float)memberCardInfo.MC_TotalMoney;
                }
                else
                {
                    result.ToMerberCardId = memberCardInfo.MC_CardID;

                    result.ToName = memberCardInfo.MC_Name;
                    result.ToPoint = (int)memberCardInfo.MC_Point;
                    result.ToTotalMoney = (float)memberCardInfo.MC_TotalMoney;
                    
                }
                return View(result);

            }



        }

        public ActionResult TransferTo(MerberCardTransferViewModel viewModel)
        {
            return View();

        }


    }
}

BGLB.MerberPoint.Web/Views/Home/Index.cshtml
@using BGLB.MerberPoint.Entity.DTOModel;
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        当前用户：
        @{ 
            var user = User as MyFormsPrincipal<LoginUserDTOModel>;
            if (user!=null && user.UserData!=null)
            {
                <span>@user.UserData.UserName</span>
            }
            else
            {
                <span>尚未登录</span>
            }
        }
    </div>

    <div>
        @Html.ActionLink("登出", "Logout", "Home");
    </div>
</body>
</html>

BGLB.MerberPoint.Web/Views/Home/Login.cshtml
@model BGLB.MerberPoint.Entity.ViewModel.LoginViewModel

@{
    /**/

    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Content/easyui/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/easyui/icon.css" rel="stylesheet" />
    <script src="~/Scripts/easyui/jquery.min.js"></script>
    <script src="~/Scripts/easyui/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui/easyui-lang-zh_CN.js"></script>

    <style>
        body {
            margin: 0;
            padding: 0;
            font-size: sans-serif;
            background: #34495e;
        }

        .box {
            width: 300px;
            padding: 40px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            background: pink;
            text-align: center;
        }

            .box h1 {
                color: white;
                text-transform: uppercase;
                font-weight: 500;
            }

            .box input[type = "text"], .box input[type = "password"] {
                border: 0;
                background: none;
                display: block;
                margin: 20px auto;
                text-align: center;
                border: 2px solid #3498db;
                padding: 14px 10px;
                width: 200px;
                outline: none;
                color: white;
                border-radius: 24px;
                transition: 0.25s;
            }

                .box input[type = "text"]:focus, .box input[type = "password"]:focus {
                    width: 280px;
                    border-color: #2ecc71;
                }

            .box input[type = "submit"] {
                border: 0;
                background: none;
                display: block;
                margin: 20px auto;
                text-align: center;
                border: 2px solid #2ecc71;
                padding: 14px 40px;
                outline: none;
                color: white;
                border-radius: 24px;
                transition: 0.25s;
                cursor: pointer;
            }

                .box input[type = "submit"]:hover {
                    background: #2ecc71;
                }
    </style>

</head>
<body>
    @using (Html.BeginForm("Login", "Home", new { ReturnUrl = Request.QueryString["ReturnUrl"] }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal ">
            <h4>LoginViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BGLB.MerberPoint.Web/Views/MeberCard/Edit.cshtml
@model BGLB.MerberPoint.Entity.ViewModel.MerberCardEditViewModel
<link href="~/Content/easyui/default/easyui.css" rel="stylesheet" />
<link href="~/Content/easyui/icon.css" rel="stylesheet" />
<script src="~/Scripts/easyui/jquery.min.js"></script>
<script src="~/Scripts/easyui/jquery.easyui.min.js"></script>
<script src="~/Scripts/easyui/easyui-lang-zh_CN.js"></script>


<script>

    $(function () {
        var postUrl = "";

        $("#btn_submit").click(function () {
            //根据隐藏域的值判断当前的操作是新增还是编辑，如果大于0说明是编辑，否则为新增
            if (parseInt($("#Id").val()) > 0) {
                postUrl = "/MeberCard/Update";
            }
            else {
                postUrl = "/MeberCard/Create";
            }

            $("#from_MerberCard").form('submit', {
                url: postUrl,
                onSubmit: function () {
                    var isValid = $(this).form('validate');
                    return isValid;//返回false终止表单提交
                },
                success: function (data) {
                    //序列化Json
                    //1.eval()
                    //var json = eval("(" + data + ")");

                    //2.
                    var json = JSON.parse(data);
                    if (json.ResultStatus == 1) {
                        //1提示消息
                        window.parent.$.messager.alert('温馨提示', json.Msg, 'info');
                        //2关闭弹窗
                        window.parent.$("#dlg").dialog("close");
                        //3刷新列表
                        window.parent.$("#dg_MerberCard").datagrid("reload");
                    }
                    else {
                        $.messager.alert('温馨提示', json.Msg, 'error');
                    }
                }
            });
        });
    });
</script>


@using (Html.BeginForm("Edit", "MeberCard", FormMethod.Post, new { id = "from_MerberCard" }))
{ 
    <fieldset>
        <legend>会员信息</legend>
        <table>
            <tr>
                <td>会员卡号</td>
                <td>@Html.TextBoxFor(model => model.CardId, new { @class = "easyui-validatebox", data_options = "required:true", missingMessage = "请输入会员卡号" })</td>
            </tr>
            <tr>
                <td>会员姓名</td>
                <td> @Html.TextBoxFor(model => model.Name, new { @class = "easyui-validatebox", data_options = "required:true", missingMessage = "请输入会员姓名" })</td>
            </tr>
            <tr>
                <td>会员电话</td>
                <td>  @Html.TextBoxFor(model => model.Mobile, new { @class = "easyui-validatebox", data_options = "required:true", missingMessage = "请输入会员电话" })</td>
            </tr>
            <tr>
                <td>会员性别</td>
                <td>@Html.EnumDropDownListFor(model => model.Sex, "请选择")</td>
            </tr>
            <tr>
                <td>会员等级</td>
                <td>  @Html.DropDownListFor(model => Model.CardLevelId, ViewBag.CardLevel as IEnumerable<SelectListItem>)</td>
            </tr>
            <tr>
                <td>当前积分</td>
                <td>  @Html.TextBoxFor(model => model.Point, new { @class = "easyui-validatebox", data_options = "required:true", missingMessage = "请输入当前积分" })</td>
            </tr>
           <tr>
                    <td>过期时间</td>
                    <td>   @Html.TextBoxFor(model =>model.PastTime,new { @class = "easyui-datebox"})</td>
                </tr>
            <tr>
                <td>卡片状态</td>
                <td>@Html.EnumDropDownListFor(model => model.CardState, "请选择")</td>
            </tr>
            <tr>
                <td>卡片付费</td>
                <td>@Html.TextBoxFor(model => model.Money, new { @class = "easyui-validatebox", data_options = "required:true", missingMessage = "请输入卡片付费数量" })</td>
            </tr>
            <tr>
                <td></td>
                <td><input type="button" id="btn_submit" value="提交" /></td>
            </tr>

        </table>
        @Html.HiddenFor(model => model.Id)
    </fieldset>

}

BGLB.MerberPoint.Web/Views/MeberCard/Index.cshtml
<link href="~/Content/easyui/default/easyui.css" rel="stylesheet" />
<link href="~/Content/easyui/icon.css" rel="stylesheet" />
<script src="~/Scripts/easyui/jquery.min.js"></script>
<script src="~/Scripts/easyui/jquery.easyui.min.js"></script>
<script src="~/Scripts/easyui/easyui-lang-zh_CN.js"></script>
<script src="~/Scripts/tools/tools.js"></script>

@using BGLB.MerberPoint.Web.Controllers

<script>
    $(function () {
        $("#dg_MerberCard").datagrid({
            fitColumns: true,//使列自动展开 或者 收缩到合适的DataGrid宽度
            toolbar: "#tb",//toolbar:通过选择器指定的工具栏
            pagination: true,//pagination：如果为True ， 则在DataGrid控件底部显示分业工具栏
            fit: true,//fit当设置为true的时候，面板大小将自适应父容器
            singleSelect: true,//如果为true 则只允许选择一行
            rownumbers: true,//如果为TRUE，则显示一个行号列
            url: "/MeberCard/GetPagedMeberCardList/",//设置能够返回Json数据的Action所对应的路径
            columns: [[
                { field: 'CardId', title: '会员卡号', width: 222, aligin: "center", },
                { field: 'Name', title: '会员姓名', width: 222, aligin: "center", },
                { field: 'Mobile', title: '手机号码', width: 222, aligin: "center", },
                { field: 'TotalMoney', title: '累计消费', width: 222, aligin: "center", },
                { field: 'State', title: '会员卡状态', width: 222, aligin: "center", },
                { field: 'Point', title: '当前积分', width: 222, aligin: "center", },
                { field: 'Sex', title: '性别', width: 222, aligin: "center", },
                { field: 'CreateTime', title: '登记时间', width: 222, aligin: "center", formatter: function (value) {return FormatJsonTime(value); }},
                { field: 'CardLevelName', title: '当前等级', width: 222, aligin: "center", }
            ]]
        });


        $("#btn_Search").click(function () {
            $("#dg_MerberCard").datagrid("load", {
                CardId: $.trim($("#txt_CardId").val()),
                Name: $.trim($("#txt_Name").val()),
                Mobile: $.trim($("#txt_Mobile").val()),
                State: $.trim($("#CardTypeSelectList").val()),
                CardLevelId: $.trim($("#CardLevel").val()),
            })
        });


        //添加
        //点击按钮弹出添加dialog对话框
        $("#btn_Create").click(function () {
            //1弹出dialog对话框
            $("#dlg").dialog({ width: 900, height: 500 }).dialog("setTitle", "添加会员").dialog("open");
            //2给iframe的src属性赋值
            //用attr找到src属性
            $("#frml").attr("src", "/MeberCard/Edit");
        });

        //编辑
        //点击按钮弹出编辑dialog对话框
        $("#btn_Edit").click(function () {
            //1判断用户是否选中行
            var row = $("#dg_MerberCard").datagrid("getSelected");
            //2如果选中打开数据弹窗，否则提示用户
            if (row == null) {
                $.messager.alert("温馨提示", "请选择要编辑的行", "warning");
            }
            else {
                //1弹出dialog对话框
                $("#dlg").dialog({ width: 900, height: 500 }).dialog("setTitle", "编辑会员").dialog("open");
                //2给iframe的src属性赋值
                $("#frml").attr("src", "/MeberCard/Edit/" + row.Id);
            }
        });
        //删除会员
        $("#btn_Delete").click(function () {
            //1判断用户是否选中行
            //2如果选中，弹出确认框，选择是否删除
            var row = $("#dg_MerberCard").datagrid("getSelected");
            if (row == null) {
                $.messager.alert("温馨提示", "请选择要删除的行", "warning");
            }
            else {
                $.messager.confirm("确认", "您确认要删除吗", function (r) {
                    if (r) {
                        $.post("/MerberCard/Delete", { id: row.Id }, function (data) {
                            if (data.ResultStatus == 1) {
                                //1提示消息
                                $.messager.alert("温馨提示", data.Msg, "info");
                                //2重新加载到数据列表
                                $("#dg_MerberCard").datagrid("reload");
                            }
                            else {
                                $.messager.alert("温馨提示", data.Msg, "error");
                            }
                        }, "json");
                    }
                });
            }
        });
        //转账
        //点击按钮弹出转账dialog对话框
        $("#btn_zhuanzhang").click(function () {
            //1判断用户是否选中行
            var row = $("#dg_MerberCard").datagrid("getSelected");
            //2如果选中打开数据弹窗，否则提示用户
            if (row == null) {
                $.messager.alert("温馨提示", "请选择要转账的会员", "warning");
            }
            else {
                //1弹出dialog对话框
                $("#dlg").dialog({ width: 900, height: 500 }).dialog("setTitle", "会员转账").dialog("open");
                //2给iframe的src属性赋值
                $("#frml").attr("src", "/MeberCard/Transfer/" + row.CardId);
            }
        });
    });

</script>
<table id="dg_MerberCard" align="center"></table>
<div id="tb" style="padding:5px;height:auto">
    <div style="margin-bottom:5px">
        <a href="#" id="btn_Create" class="easyui-linkbutton" iconCls="icon-add">新增</a>
        <a href="#" id="btn_Edit" class="easyui-linkbutton" iconCls="icon-edit">修改</a>
        <a href="#" id="btn_Delete" class="easyui-linkbutton" iconCls="icon-remove">删除</a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-lock">锁定/挂失</a>
        <a href="#" id="btn_zhuanzhang" class="easyui-linkbutton" iconCls="icon-filter">会员转账</a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-reload">会员换卡</a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-sum">导出Excel</a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-tip">导入Excel</a>
    </div>
    <div>
        会员卡号: <input id="txt_CardId" type="text" class="easyui-textbox" />
        会员姓名: <input id="txt_Name" type="text" class="easyui-textbox" />
        电话: <input id="txt_Mobile" type="text" class="easyui-textbox" />
        会员等级:@Html.DropDownList("CardLevel", ViewBag.CardLevel as IEnumerable<SelectListItem>)
        状态: @Html.DropDownList("CardTypeSelectList", ViewBag.CardTypeSelectList as IEnumerable<SelectListItem>)
        <a href="#" id="btn_Search" class="easyui-linkbutton Search" iconCls="icon-search">查询</a>
    </div>
</div>
<div id="dlg" class="" data-options="iconCls:'icon-save',resizable:true,model:true,closed:true">
    <iframe id="frml" width="99%" height="99%" frameborder="0"></iframe>
</div>

BGLB.MerberPoint.Web/Views/MeberCard/Transfer.cshtml
@model BGLB.MerberPoint.Entity.ViewModel.MerberCardTransferViewModel
<link href="~/Content/easyui/default/easyui.css" rel="stylesheet" />
<link href="~/Content/easyui/icon.css" rel="stylesheet" />
<script src="~/Scripts/easyui/jquery.min.js"></script>
<script src="~/Scripts/easyui/jquery.easyui.min.js"></script>
<script src="~/Scripts/easyui/easyui-lang-zh_CN.js"></script>

<script>
    $(function () {
        $('#btn_Query').click(function () {
            //获取要查询的卡号  $("#IdCard").val()

            var ids = $("#IdCard").val();
            console.log(ids);
            $.post("/MeberCard/Transfer", { id: ids }, function (data) {
                console.log(data);
                $("#ToMeberCardId").val(data.ToMeberCardId);
                $("#ToName").val(data.ToName);
                $("#ToPoint").val(data.ToPoint);
                $("#ToTotalMoneys").val(data.ToTotalMoneys);
                   // $.messager.alert('温馨提示', data.Msg, 'error');              
            }, "json");


        });
        $("#btn_Zhuan").click(function () {
            $("#MeberCardTransferList").form('submit', {
                url: '/MeberCard/Transfer',
                onSubmit: function () {
                    var isValid = $(this).form('validate');
                    return isValid;//返回false终止表单提交
                },
                success: function (data) {
                    //序列化Json
                    //1.eval()
                    //var json = eval("(" + data + ")");
                    //2.
                    var json = JSON.parse(data);
                    if (json.ResultStatus == 1) {
                        //1提示消息
                        window.parent.$.messager.alert('温馨提示', json.Msg, 'info');
                        //2关闭弹窗
                        window.parent.$("#dlg").dialog("close");

                    }
                    else {
                        $.messager.alert('温馨提示', json.Msg, 'error');
                    }
                }
            });
        });
    });
</script>

@using (Html.BeginForm("Transfer", "MeberCard", FormMethod.Post, new { id = "MeberCardTransferList" }))
{
    <fieldset style=" width:60%; height:auto;margin:auto">
        <legend>会员转账</legend>
        <fieldset>
            <legend>转账会员</legend>
            <table>
                <tr>
                    <td>卡&emsp;号:</td>
                    <td>@Html.TextBoxFor(model => model.FromMerberCardId, new { @class = "easyui-validatebox", @readonly = true })</td>
                    <td>姓&emsp; 名:</td>
                    <td>@Html.TextBoxFor(model => model.FromName, new { @class = "easyui-validatebox", @readonly = true })</td>
                </tr>
                <tr>
                    <td>账户积分:</td>
                    <td>@Html.TextBoxFor(model => model.FromTotalMoney, new { @class = "easyui-validatebox", @readonly = true })</td>
                    <td>累计消费:</td>
                    <td>@Html.TextBoxFor(model => model.FromTotalMoney, new { @class = "easyui-validatebox", @readonly = true })</td>
                </tr>
            </table>
        </fieldset>
        <p>点击查找获取当前输入会员信息</p>
        <input type="text" id="IdCard" />
        <input type="button" value="查找" style="background-color:lightskyblue ; width:50px" id="btn_Query" />

        <fieldset>
            <legend>收款会员</legend>

            <table>
                <tr>
                    <td>卡&emsp;号:</td>
                    <td>@Html.TextBoxFor(model => model.ToMerberCardId, new { @class = "easyui-validatebox", @readonly = true })</td>
                    <td>姓&emsp;名:</td>
                    <td>@Html.TextBoxFor(model => model.ToName, new { @class = "easyui-validatebox", @readonly = true })</td>
                </tr>
                <tr>
                    <td>账户积分:</td>
                    <td>@Html.TextBoxFor(model => model.ToPoint, new { @class = "easyui-validatebox", @readonly = true })</td>
                    <td>累计消费:</td>
                    <td>@Html.TextBoxFor(model => model.ToTotalMoney, new { @class = "easyui-validatebox", @readonly = true })</td>
                </tr>
            </table>
        </fieldset>
        <table>
            <tr>
                <td>转账金额:</td>
                <td>@Html.TextBoxFor(model => model.TransferMoney, new { @class = "easyui-validatebox", data_options = "required:true", @missingMessage = "必填" })</td>
            </tr>
            <tr>
                <td>操作备注:</td>
                <td>@Html.TextBoxFor(model => model.Remark, new { @class = "easyui-validatebox", data_options = "required:true", @missingMessage = "必填" })</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="button" value="转账" style="background-color:lightskyblue;width:50px" id="btn_Zhuan" />
                </td>
            </tr>
        </table>


    </fieldset>
}

BGLB.MerberPoint.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/easyui")
    @Scripts.Render("~/bundles/easyui")

</head>
<body>

    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>

    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
    </footer>

</body>
</html>